# Generated by Django 2.0.2 on 2018-02-16 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mazolutions', '0002_auto_20180215_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazolutionstep',
            name='mazolution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_mazolution', to='Mazolutions.Mazolution'),
        ),
        migrations.AlterField(
            model_name='mazolutionstep',
            name='reference_mazolution',
            field=models.ForeignKey(on_delete=None,  related_name='reference_mazolution', to='Mazolutions.Mazolution'),
        ),
    ]
