# Generated by Django 2.0.2 on 2018-02-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mazolutions', '0004_auto_20180216_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazolutionstep',
            name='reference_mazolution',
            field=models.ForeignKey(default=None, null=True, on_delete=None, related_name='reference_steps', to='Mazolutions.Mazolution'),
        ),
    ]
